all:
	fpc -FE./bin ./src/125rzaev_bubble_less.pas
	fpc -FE./bin ./src/125rzaev_bubble_greater.pas
	fpc -FE./bin ./src/125rzaev_qsort_less.pas
	fpc -FE./bin ./src/125rzaev_qsort_greater.pas
	rm ./bin/*.o
